### ISSUE TITLE
Smaller repository (gh-pages pdfs)

### ISSUE THREAD

**Issue by 153957** [HiSPARC/infopakket#23]
Every time we update the `gh-pages` each pdf that git detects as changed is replaced entirely.
For example: 75f9bccc80, 6fbd53b1a6cb83, 7bbc25843baacd.

Because of this the repository had grown very large, my local copy is 300 MB, while the code/images in `master` are 'only' 27 MB (mostly due to some images), and the size of the `gh-pages` branch is similar (28 MB).

So the largest part is the history of the `gh-pages` branch. Perhaps we can change the Make script to delete the history of the `gh-pages` branch each time and keep only the latest version. Im not certain how that would work with syncing.. perhaps delete the branch and recreate it? Any ideas? git magic?

@davidfokkema

**Comment by davidfokkema** [comment]
Throwing away all history and creating a new branch will result in sync errors. You'll have to force pulling in the changes and overwriting your local branch. This s*cks big time. I'll have to sleep on this. Ideas most welcome.

**Comment by 153957** [comment]
We can so some fancy things in the Makefile,

- First force pull the gh-pages branch
    - To make sure you have internet and are up to date.
- use filter-branch to remove all pdfs from the gh-pages branch
    - https://help.github.com/articles/remove-sensitive-data/
    - http://git-scm.com/docs/git-filter-branch
    - git rm
    - index-filter
- make the new pdfs, do the commit
- force push the gh-pages branch

**Comment by 153957** [comment]
If we use the method proposed here: HiSPARC/sapphire#177 this would be solved.
Travis builds would be quite slow because they need to install LateX and build all documents, example:
https://mirocupak.com/continuous-integration-for-latex/
https://travis-ci.org/mcupak/beacon-network-poster-ashg

**Comment by 153957** [comment]
@davidfokkema / @tomkooij Are you having any issues with git and sapphire/jsparc/etc, since those now throw away the gh-pages branch each time? I think we can make this work similar to those.

Except perhaps for the automated builds, that is still tricky on Travis..
Maybe this more updated example works, I will setup a branch to test that: https://github.com/PHPirates/travis-ci-latex-pdf

**Comment by davidfokkema** [comment]
No issues so far, just did an update. It seems that you should never feel the need to checkout the gh-pages branch anymore?

**Comment by 153957** [comment]
Indeed, only to easily access the pdfs without having to build them yourself or having to download them all. But downloading is also easy via https://github.com/HiSPARC/infopakket/archive/gh-pages.zip

**Comment by 153957** [comment]
See #43

**Comment by 153957** [comment]
Checkout of old repo: 197 MB
Checkout of current repo: 96 MB
The repo should no longer increase in size as fast (each gh-pages update) as before.
