### ISSUE TITLE
Use notedown to keep ipynb as markdown in master

### ISSUE THREAD

**Issue by 153957** [HiSPARC/infopakket#33]
The md files can be converted to ipynb when generating the gh-pages.

`notedown input.md > output.ipynb`

See https://github.com/aaren/notedown

Using markdown as IPython Notebook sources has the advantage that the commits and diffs are clearer.
When working with the source code, i.e. editing the notebooks this can be done on the markdown files by configuring IPython with: `c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'`

**Comment by 153957** [comment]
This is being used in #32. Unfortunately https://github.com/aaren/notedown/pull/46 is not yet merged, once it is we should use `notedown.NotedownContentsManagerStripped` for cleaner output.

**Comment by 153957** [comment]
Currently some urls are broken in the .md files, are remain broken when converter back to ipynb. Issue is reported in https://github.com/aaren/notedown/issues/49

**Comment by 153957** [comment]
Both issues reported above have been fixed! It should now be easy to edit in Jupyter and save to stripped markdown files. Moreover, links should remain safe.

**Comment by tomkooij** [comment]
Nice!

**Comment by 153957** [comment]
I updated the notebook README. Once a new version of notedown is put on PyPI we should simply recommend `pip install notedown` instead of referring to the github page.
