### ISSUE TITLE
gh-pages niet pushen: Notebooks urls stuk

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/infopakket#35]
Ik heb net per ongeluk de branch notebooks gemerged... (zucht!)

Op zich niet heel erg, want de PR was af, maar helaas zorgt een bug in notedown ervoor dat de URLs in notebook stuk zijn: #33

Totdat dit is opgelost `gh-pages` niet maken/pushen!

**Comment by tomkooij** [comment]
Line-breaks verwijderd in: a492b46
Met aangepast `notedown` (aaren/notedown#50) gh-pages gemaakt en gepushed.

De huidige `master` staat nu op docs.hisparc.nl, maar geen nieuwe pushen zonder eerst `notedown` te patchen.

**Comment by 153957** [comment]
Fixed in the master of notedown, not yet released to PyPI.
