### ISSUE TITLE
Transition to Python 3

### ISSUE THREAD

**Issue by 153957** [HiSPARC/infopakket#38]
Python 2 will be end-of-life in a few years.
The infopakket should be transitioned to Python 3.
SAPPHiRE is already Python 3 compatible.
It would probably be best to keep backwards compatibility with Python 2 for now.

Python parts:
- [x] Notebooks
- [x] `generate_index.py`
- ~~code examples?~~

See discussion at: HiSPARC/sapphire#154 (comment)

**Comment by tomkooij** [comment]
`generate_index.py`: fixed in e984d1e and de831b0 . We can now generate the infopakket on python 3.

Notebooks: I intend to add `from __future__ import division, print_function` to all notebooks and use `print()` everywhere/

**Comment by tomkooij** [comment]
Notebooks fixed for python 3 in #39.

**Comment by 153957** [comment]
Are there any Python examples in the other infopakket documents?
Or are the only code examples the C examples for Arduino?

**Comment by 153957** [comment]
Still some Python 2.7 references in `notebook_installatie`

**Comment by 153957** [comment]
Fixed remaining 2.7 references in 41decfc
