### ISSUE TITLE
Store infopakket notebooks without generated output

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/infopakket#40]
Feedback from `VWO leerlingen` that worked through the notebooks:

> While using the notebooks, it is both confusing and annoying that a fresh downloaded notebook from the infopakket already shows output. At first this output was interpreted as results of a "run" of the notebook upon opening. This is ofcourse incorrect and confusing.
> While using the notebook it is confusing that "real" output is confused with old/stale ouput.

Suggestion: remove  / clean the output of the notebooks in the infopakket.

**Comment by 153957** [comment]
Which ones include output? I see that most (randomly checked a few) `.md` notebooks in the notebooks dir have no output.

**Comment by tomkooij** [comment]
Interesting. This was feedback from students (VWO leerlingen) from the Leiden cluster.
Perhaps they were re-using notebooks and/or using notebooks we have preinstalled on our Jupyterhub server. 

So this is not an infopakket issue.

I'll leave this open for now, because it might need fixing on our Jupyterhub.
