### ISSUE TITLE
10_sterrenkaart, milky_way.npy ontbreekt?

### ISSUE THREAD

**Issue by deKeijzer** [HiSPARC/infopakket#46]
Klopt het dat de bestanden 'milky_way.npy' en 'milky_way_polar.npy' ontbreken? Zouden de bestanden of een bron naar de arrays toegevoegd kunnen worden?

**Comment by tomkooij** [comment]
Bedankt voor het melden. Ze komen zsm weer online.

**Comment by tomkooij** [comment]
Fixed in f9c3b7645b0bf0e568cf987de09bab4cc9b5bdb1
