### ISSUE TITLE
Hoofdstuk theorie en werkblad gescheiden?

### ISSUE THREAD

**Issue by montanush** [HiSPARC/infopakket#8]
Ik ben bezig met een hoofdstuk air showers in de categorie theorie (algemeen). De opzet is zodanig dat er een aantal vragen/opdrachten over gegeven kunnen worden. Dat doe ik voorlopig in een apart werkblad. Dat heeft als voordeel dat het duidelijk is dat alle vragen/opdrachten in werkbladen staan. Maar het heeft als consequentie dat het de docent (die er een les aan wil besteden) duidelijk moet zijn dat er een werkblad hoort bij het theorie hoofdstuk.  Er komen dan 3 situaties:
- zelfstandige hoofdstukken (dus zonder bijbehorend werkblad)
- hoofdstukken met bijbehorend werkblad
- zelfstandige werkbladen (zonder bijbehorend hoofdstuk)

Is dit wat we willen? Hoe en waar leggen we dat uit in het INFOPAKKET?

**Comment by 153957** [comment]
Seems this is fixed now with the exam class, and `style_werkblad`.
An example can be seen here: https://github.com/HiSPARC/infopakket/tree/master/cosmic_showers
